### ISSUE TITLE
Читать + слушать

### ISSUE THREAD

**Issue by frebrain** [kolyvan/bilibre#3]
Приветствую.
Просто Огромная просьба к разработчику. 
Сделайте возможным чтение и прослушивание одновременным. На данный момент это делать просто невозможно из-за функции автоматического перелистывания и перепрыгивания "голосового чтения" по тексту. 
Прошу вас сделать возможным самостоятельно двигать текст при голосовом чтении, чтобы можно было спокойно слушать + читать и не нервничать от постоянно прыгающего текста.
Так же, наверняка, встанет проблема поиска места на котором сейчас идет голосовое чтение. Предлагаю просто при нажатии пауза + play "прыгать" на читаемую область.

Заранее благодарю вас. Вроди элементарная вещь, но без нее невозможно наслаждаться чтением и прослушиванием одновременно.

**Comment by kolyvan** [comment]
В приложении BiLibre нет автоматической смены позиции чтении при синтезе речи.  Простите но по видимому Вы ошиблись страницей.
